version: 0.2
phases:
  install:
    commands:
       - echo Installing source NPM dependencies...
       - npm install -g @angular/cli
  pre_build:
    commands:
      - npm update npm - g
      - rm -rf node_modules/
      - npm install
  build:
    commands:
       - echo Build started on `date`
       - ng build

artifacts:
  files:
    - '**/*'
